version: '3.3'

services:
  php:
    build: ./
    volumes:
      - ./code_source:/var/www/html
      - ./conf/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    ports:
      - 8000:8000
    extra_hosts:
      - host.docker.internal:host-gateway